apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nosqlclaim-reaper
rules:
  - apiGroups: ["platform.example.org"]
    resources: ["storage", "awsstorage"]
    verbs: ["*"]
