apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: claim-reaper
rules:
  - apiGroups: ["platform.example.org"]
    resources: ["storage", "awsstorage", "compute", "awscompute"]
    verbs: ["*"]
