apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
#        volumeMounts:
#        - name: kubeconfig
#            mountPath: /root/.kube
#            readOnly: true
 #     volumes:
 #       - name: kubeconfig
 #         hostPath:
 #           path: /Users/YOUR_USERNAME/.kube # Adjust for your system
