apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-platform
  namespace: argocd
spec:
  project: k8s-platform
  source:
    repoURL: https://github.com/CarlosLaraFP/k8s-platform.git
    targetRevision: main
    path: infra
    directory:
      recurse: true
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
