apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket-aws
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: XBucket
  resources:
    - name: s3bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            acl: private
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: "spec.bucketName"
          toFieldPath: "metadata.name"
