apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-user
  namespace: default
rules:
  - apiGroups: ["platform.example.org"]
    resources: ["buckets", "buckets/status", "nosqls", "nosqls/status"]
    verbs: ["get", "list", "watch", "create", "delete"]
