apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: "10Mi"
        cpu: "250m"
      limits:
        memory: "20Mi"
        cpu: "500m"