apiVersion: apiextensions.crossplane.io/v1
kind: Composition # encapsulates 1+ AWS resources with patchable parameters
metadata:
  # You could compose AWS + GCP + on-prem resources in one
  # You could compose Kubernetes-native resources only (like ConfigMap, Deployment, etc.)
  # You could even use fake CRDs (e.g., FakeDatabase) to simulate training/demo environments
  name: bucket-aws
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: XBucket
  mode: Pipeline
  pipeline:
    #- functionRef:
    #    type: Container
    #    container:
    #      image: ghcr.io/YOUR_USERNAME/xfn-random-name:v0.1.0
    - step:
        name: create-bucket
        base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: Bucket
          spec:
            forProvider:
              acl: private
            providerConfigRef:
              name: default
    # - name: iamRole
    #   base:
    #     apiVersion: iam.aws.upbound.io/v1beta1
    #     ind: Policy
