apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: claim-expirer
  namespace: default
rules:
- apiGroups: ["platform.example.org"]
  resources: ["nosqlclaims"]
  verbs: ["get", "list", "watch", "delete"]
