apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  namespace: argocd
spec:
  project: k8s-platform
  source:
    repoURL: https://github.com/CarlosLaraFP/k8s-platform.git
    targetRevision: main
    path: infra/apps/00-crossplane-providers
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  # 👇 ensures this is synced before the next step
  syncWave: "0"
