apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-bucket
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CarlosLaraFP/k8s-platform
    targetRevision: HEAD
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
